name: ci

on:
  push:
    branches:
      - 'feature/13/gitactions-ci-cd'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          workdir: ./cmd/orchestrator
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#      - name: Deploy
#        uses: deliverybot/helm@master
#        with:
#          token: ${{ secrets.GH_TOKEN }}
#          # still in tests
#          #secrets: ${{ toJSON(secrets) }}
#          chart: app
#          namespace: production
#          release: production-myapp
#        env:
#          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}