name: test

on:
  push:
    branches:
      - 'feature/13/gitactions-ci-cd'
  pull_request:
    branches:
      - 'feature/13/gitactions-ci-cd'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Validate
        uses: docker/bake-action@v1
        with:
          targets: validate
      -
        name: Test
        uses: docker/bake-action@v1
        with:
          targets: test